name: neon-back-workflow

on:
  pull_request

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: run test
        run: npm i && npm test
      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zeon-back:latest
          name: jest-and-docker-ci
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  